### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by tony-gutierrez** [fmvilas/swagger-node-codegen-cli#1] opened 2017-10-26 17:38 UTC
Generating project...
Aaww 💩. Something went wrong:
Cannot read property 'split' of undefined

No further info, no verbose flag?

**Comment by fmvilas** [comment] 2017-10-27 14:03
I'm sorry, I have this project kind of abandoned. I'll take a look at it if I have time but would very much appreciate a PR.

**Comment by epeld** [comment] 2017-12-15 14:24
For what it's worth, this error happened to me because one of my endpoints had a summary but not a description..!

**Comment by fmvilas** [comment] 2017-12-15 16:39
Thanks @epeld. Will appreciate a PR :blush:

**Comment by fmvilas** [comment] 2017-12-16 10:51
I'm working on a fix right now and can't reproduce it. Can you please provide a minimal example? @tony-gutierrez @epeld

**Comment by fmvilas** [comment] 2017-12-16 11:17
I'm working on a fix right now and can't reproduce it. Can you please provide a minimal example? @tony-gutierrez @epeld

**Comment by epeld** [comment] 2017-12-16 12:47
@fmvilas 

Here is a small example that doesn't make much sense but reproduces the problem at least: 

```
swagger: '2.0'
info:
  description: "This is the Test Test App API"
  version: 1.0.0
  title: TestApp
host: localhost:8080
basePath: api/v1
produces:
  - application/json
consumes:
  - application/json
tags:
  - name: test
    description: Endpoints
schemes:
  - http
parameters:
  ip:
    name: ip
    in: query
    description: 'IP address of test to request clients in, defaults to request origin'
    type: string
    required: false
paths:
  /is-test:
    get:
      summary: "Check if a test exists"
      operationId: isTest
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/ip'
      responses:
        '200':
          description: OK

```

If I add a line
```
     description: "FOO"
```
just before
```
      summary: "Check if a test exists"
```
then it works again

**Comment by fmvilas** [comment] 2017-12-18 18:23
Thanks, @epeld. It helped a lot. I just release a new major version of the package here: https://github.com/fmvilas/swagger-node-codegen (I merged both packages: CLI and module).

It now has OpenAPI 3 support as well. Hope it helps!

/cc @tony-gutierrez

**Closed as completed** 2017-12-20 00:18 UTC
Labels: bug
